---
abstract: 'distribute rounding errors fairly'
author:
  - 'Marc Mims <marc@questright.com>, Anders Johnson <anders@ieee.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  List::Util: 0
  Math::CDF: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Math::Round::Fair
name: Math-Round-Fair
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Devel::Assert: 0
  Exporter: 0
  Perl6::Junction: 0
  perl: 5.005
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Math-Round-Fair
  homepage: http://github.com/semifor/math-round-fair
  license: http://dev.perl.org/licenses/
  repository: git://github.com/semifor/math-round-fair.git
version: 0.02
